version: '3.3'
services:
  painel_de_atendimento_web:
    build: .
    image: painel_de_atendimento_web:latest
    restart: always
    ports:
      - 80:80 # WEB
    volumes:
      - ./www/:/var/www/html/
    deploy:
      resources:
        limits:
#          cpus: '1.0'
          memory: 400M
#        reservations:
#          cpus: '0.25'
#          memory: 40M
#        memswap_limit: 600M
    env_file:
      - .env
 
networks:
  default:
    external: true
    name: default-network
