version: '3.3'
services:
  web:
#    image: tomsik68/xampp:8
    build: .
    restart: always
    links:
      - mysql
    ports:
      - 80:80
    volumes:
      - ./www/app:/opt/lampp/htdocs/app
      - ./www/lib:/opt/lampp/htdocs/lib
      - ./www/public:/opt/lampp/htdocs/public
      - ./www/storage:/opt/lampp/htdocs/storage
      - ./www/adm:/opt/lampp/htdocs/adm
      - ./www/.htaccess:/opt/lampp/htdocs/.htaccess
      - ./www/composer.json:/opt/lampp/htdocs/composer.json
      - ./www/composer.lock:/opt/lampp/htdocs/composer.lock
      - ./www/index.php:/opt/lampp/htdocs/index.php
#      - ./www:/opt/lampp/htdocs
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database_example
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    restart: always
    links:
      - mysql
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
  adminer:
    image: adminer:4.8.1
    restart: always
    links:
      - mysql
    ports:
      - 82:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    volumes:
      - /etc/localtime:/etc/localtime

#networks:
#  default:
#    external: true
#    name: default-network
