version: '3.3'
services:
  web:
    build: .
    restart: always
    ports:
      - 80:80
    volumes:
      - ./www/:/var/www/html/
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 400M
        reservations:
          cpus: '0.25'
          memory: 40M
    memswap_limit: 600M
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
      - rabbitmq

  mysql:
    image: mysql:8.0.32
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data-mysql/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database_example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    hostname: phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql

  adminer:
    image: adminer:4.8.1
    hostname: adminer
    restart: always
    links:
      - mysql
    ports:
      - 82:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    volumes:
      - /etc/localtime:/etc/localtime
    depends_on:
      - mysql

# https://hub.docker.com/r/bitnami/redis/
  redis:
    image: bitnami/redis:7.0.8
    hostname: redis
    restart: always
#    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    ports:
      - 6379:6379
    volumes:
      - ./data-redis/redis-persistence:/bitnami/redis/data
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
      - REDIS_PASSWORD=password
#      - REDIS_USERNAME=root
#      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
#      - REDIS_IO_THREADS=4
#      - REDIS_IO_THREADS_DO_READS=true
#      - REDIS_AOF_ENABLED=no

# https://hub.docker.com/r/rediscommander/redis-commander
# https://github.com/joeferner/redis-commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    restart: always
    links:
      - redis
    ports:
      - 8081:8081
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
#      - REDIS_USERNAME=user
#      - HTTP_USER=user
#      - HTTP_PASSWORD=password
    depends_on:
      - redis

# https://medium.com/xp-inc/rabbitmq-com-docker-conhecendo-o-admin-cc81f3f6ac3b
  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 25676:25676
    volumes:
      - ./data-rabbitmq/rabbitmq_log:/var/log/rabbitmq
      - ./data-rabbitmq/rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

#networks:
#  default:
#    external: true
#    name: default-network
