version: '3.3'
services:
  web:
    build: .
    image: continuum_web:latest
    restart: always
    ports:
      - 80:80 # WEB
    #volumes:
    #  - ./www/app/:/var/www/html/app/
    #  - ./www/lib/:/var/www/html/lib/
    #  - ./www/storage/:/var/www/html/storage/
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 768M
    #    reservations:
    #      cpus: '0.5'
    #      memory: 512M
    #    memswap_limit: 1024M
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
      - rabbitmq

  mysql:
    image: mysql:8.4.1
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume1:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database_example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    hostname: phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 81:80 # WEB
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql

  adminer:
    image: adminer:4.8.1
    hostname: adminer
    restart: always
    links:
      - mysql
    ports:
      - 82:8080 # WEB
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    volumes:
      - /etc/localtime:/etc/localtime
    depends_on:
      - mysql

  # https://hub.docker.com/r/bitnami/redis/
  redis:
    image: bitnami/redis:7.4
    hostname: redis
    restart: always
    #    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    ports:
      - 6379:6379
    volumes:
      - redis-volume1:/bitnami/redis/data
    environment:
      #      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
      - REDIS_PASSWORD=password
  #      - REDIS_USERNAME=root
  #      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
  #      - REDIS_IO_THREADS=4
  #      - REDIS_IO_THREADS_DO_READS=true
  #      - REDIS_AOF_ENABLED=no

  # https://hub.docker.com/r/rediscommander/redis-commander
  # https://github.com/joeferner/redis-commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    restart: always
    links:
      - redis
    ports:
      - 8081:8081 # WEB
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    #      - REDIS_USERNAME=user
    #      - HTTP_USER=user
    #      - HTTP_PASSWORD=password
    depends_on:
      - redis

  # https://medium.com/xp-inc/rabbitmq-com-docker-conhecendo-o-admin-cc81f3f6ac3b
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672 # WEB
      - 25676:25676
    volumes:
      - rabbitmq-volume1:/var/log/rabbitmq
      - rabbitmq-volume2:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  mysql-volume1:
    driver: local
  redis-volume1:
    driver: local
  rabbitmq-volume1:
    driver: local
  rabbitmq-volume2:
    driver: local

#networks:
#  default:
#    external: true
#    name: default-network
