#!/usr/bin/env php
<?php

ini_set("default_charset", "utf-8");
ini_set("set_time_limit", "86400");
ini_set("max_execution_time", "86400");
ini_set("default_socket_timeout", "86400");
ini_set("max_input_time", "86400");
ini_set("max_input_vars", "6000");
ini_set("memory_limit", "6144M");
ini_set("post_max_size", "6144M");
ini_set("upload_max_filesize", "6144M");
ini_set("max_file_uploads", "200");

require_once __DIR__ . "/lib/DataManager.php";

use Lib\DataManager;

$nameFunction = $argv[1] ?? "";
$nameFile = $argv[2] ?? "";
$require = $argv[3] ?? false;
if (isset($argv[4])) {
    $require = array_slice($argv, 3);
}

$cmd = strtolower($nameFunction);

if (!empty($nameFunction) && !empty($nameFile)) {
    require_once __DIR__ . "/lib/cli.php";
    fun_switch_app_options($cmd, $nameFile, $require);
    die;
} else if (!empty($nameFunction)) {
    if ($nameFunction == "zip" || $nameFunction == "z" || $nameFunction == "unzip" || $nameFunction == "uz") {
        $path = DataManager::path(__DIR__ . "/vendor/");
        if (DataManager::exist($path) == "FOLDER") {
            $mode = $cmd;
            DataManager::zipUnzipFolder($path, $mode);
        }
    } else {
        require_once __DIR__ . "/lib/cli.php";
        fun_switch_other_options($cmd);
    }
    die;
}

require_once __DIR__ . "/lib/cli.php";
fun_list_commands();


/*

composer dump-autoload
composer.json(PSR-4)
{
    "autoload": {
        "psr-4": {
            "App\\" : "app/"
        }
    }
}

composer.json(Classmap)
{
    "autoload": {
        "classmap": ["Vendas", "Estoque"]
    }
}

*/
